---
- hosts: Controller
  name: gather ceph mon nodes
  tasks:
    - name: remove previous inventory file if present
      file:
        path: /tmp/shrink-inventory.yml
        state: absent
      delegate_to: localhost
      run_once: true
    - name: create inventory file
      file:
        path: /tmp/shrink-inventory.yml
        state: touch
      delegate_to: localhost
      run_once: true
    - command: hostname -s
      register: mon_hostnames
    - name: Create MON hostgroup in inventory file
      lineinfile:
        line: "[mons]"
        dest: "/tmp/shrink-inventory.yml"
        insertafter: EOF
      delegate_to: localhost
    - name: Append MON hostnames to inventory file
      lineinfile:
        line: "{{ item }} ansible_ssh_user=heat-admin"
        dest: "/tmp/shrink-inventory.yml"
        insertafter: EOF
      delegate_to: localhost
      with_items: "{{ mon_hostnames.stdout }}"

- hosts: CephStorage
  name: gather ceph osd nodes
  tasks: 
    - command: hostname -s
      register: osd_hostnames
    - name: Create OSD hostgroup in inventory file
      lineinfile:
        line: "[osds]"
        dest: "/tmp/shrink-inventory.yml"
        insertafter: EOF
      delegate_to: localhost
    - name: Append OSD hostnames to inventory file
      lineinfile:
        line: "{{ item }} ansible_ssh_user=heat-admin"
        dest: "/tmp/shrink-inventory.yml"
        insertafter: EOF
      delegate_to: localhost
      with_items: "{{ osd_hostnames.stdout }}"

- hosts:
    - Controller
    - CephStorage
  name: Configure /etc/hosts
  tasks:
    - shell: grep $(hostname).ctlplane /etc/hosts|awk '{print $1, $3}'|sed 's/\.ctlplane//g'
      register: hostnames
    - name: Append hostnames and IPs to /etc/hosts
      lineinfile:
        line: "{{ item }}"
        dest: "/etc/hosts"
        insertafter: EOF
        regexp: "^.* {{ item.split(' ')[1] }}"
      delegate_to: localhost
      become: true
      with_items: "{{ hostnames.stdout }}"
